"""Parity tests for the backend live UWB link selector.

BLF-003: this is a behavior-preserving port of
``viewer/src/simulation/uwbLinkSelection.ts``. The unit cases mirror
``uwbLinkSelection.test.ts`` one to one, and the fixture test replays
scenarios generated by the TypeScript selector
(``tests/fixtures/uwb_selection_parity.json``) so cross-language drift in
ordering, hysteresis, or the angle gate fails loudly.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from swarmfix.live.models import LiveUwbMeasurement, SelectedUwbLink
from swarmfix.live.uwb_selection import (
    LiveUwbSelectionOptions,
    select_live_uwb_links,
    stable_uwb_endpoint_key,
)

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "uwb_selection_parity.json"

SQUARE_ROOT_2 = math.sqrt(2.0)

BASE_POSITIONS = {
    "agent_0": (0.0, 0.0, 0.0),
    "agent_1": (1.0, 0.0, 0.0),
    "agent_2": (0.0, 0.0, 1.0),
    "agent_3": (3.0, 0.0, 0.0),
}


def uwb(source_id: str,
        target_id: str,
        distance_m: float,
        sigma_m: float = 0.1) -> LiveUwbMeasurement:
    """Return one candidate UWB measurement for selector tests."""
    measurement = LiveUwbMeasurement(
        source_id=source_id,
        target_id=target_id,
        distance_m=distance_m,
        sigma_m=sigma_m,
        true_distance_m=distance_m,
    )
    return measurement


BASE_MEASUREMENTS = [
    uwb("agent_0", "agent_3", 3.0, sigma_m=0.3),
    uwb("agent_0", "agent_1", 1.0),
    uwb("agent_1", "agent_2", SQUARE_ROOT_2),
    uwb("agent_0", "agent_2", 1.0),
]

BASE_OPTIONS = LiveUwbSelectionOptions(
    max_links_per_agent=2,
    max_range_m=2.0,
    add_range_m=1.9,
    drop_range_m=2.2,
    max_graph_changes_per_frame=10,
)


def selected_keys(selection) -> list[str]:
    keys = [
        stable_uwb_endpoint_key(link.source_id, link.target_id)
        for link in selection.selected_links
    ]
    return keys


def test_builds_deterministic_range_filtered_candidates() -> None:
    selection = select_live_uwb_links(
        positions=BASE_POSITIONS,
        measurements=BASE_MEASUREMENTS,
        options=BASE_OPTIONS,
    )

    assert [candidate.distance_m for candidate in selection.candidates] == [
        1.0,
        1.0,
        SQUARE_ROOT_2,
    ]
    assert [candidate.key for candidate in selection.candidates] == [
        "agent_0::agent_1",
        "agent_0::agent_2",
        "agent_1::agent_2",
    ]
    assert selection.diagnostics.candidate_link_count == 3


def test_prefers_shorter_links_while_respecting_degree_cap() -> None:
    options = LiveUwbSelectionOptions(
        max_links_per_agent=1,
        max_range_m=4.0,
        add_range_m=4.0,
        drop_range_m=2.2,
        max_graph_changes_per_frame=10,
    )

    selection = select_live_uwb_links(
        positions=BASE_POSITIONS,
        measurements=BASE_MEASUREMENTS,
        options=options,
    )

    assert len(selection.selected_links) == 1
    only_link = selection.selected_links[0]
    assert (only_link.source_id, only_link.target_id) == ("agent_0", "agent_1")
    assert only_link.measured_distance_m == 1.0
    assert only_link.sigma_m == 0.1
    assert only_link.selection_reason == "new"
    assert selection.diagnostics.selected_link_count == 1


def test_prioritizes_underconnected_agents_before_densifying_a_pair() -> None:
    chain_positions = {
        "agent_0": (0.0, 0.0, 0.0),
        "agent_1": (1.0, 0.0, 0.0),
        "agent_2": (2.0, 0.0, 0.0),
        "agent_3": (3.0, 0.0, 0.0),
    }
    chain_measurements = [
        uwb("agent_0", "agent_1", 1.0),
        uwb("agent_1", "agent_2", 1.0),
        uwb("agent_0", "agent_2", 2.0),
        uwb("agent_2", "agent_3", 1.0),
    ]
    options = LiveUwbSelectionOptions(
        max_links_per_agent=2,
        max_range_m=3.0,
        add_range_m=3.0,
        drop_range_m=2.2,
        max_graph_changes_per_frame=10,
    )

    selection = select_live_uwb_links(
        positions=chain_positions,
        measurements=chain_measurements,
        options=options,
    )

    assert "agent_2::agent_3" in selected_keys(selection)


def test_prefers_triangle_closure_after_basic_coverage_exists() -> None:
    selection = select_live_uwb_links(
        positions=BASE_POSITIONS,
        measurements=BASE_MEASUREMENTS,
        options=BASE_OPTIONS,
    )

    assert selected_keys(selection) == [
        "agent_0::agent_1",
        "agent_0::agent_2",
        "agent_1::agent_2",
    ]
    assert selection.diagnostics.triangle_count == 1


def test_does_not_rate_limit_the_initial_graph_fill() -> None:
    options = LiveUwbSelectionOptions(
        max_links_per_agent=2,
        max_range_m=2.0,
        add_range_m=1.9,
        drop_range_m=2.2,
        max_graph_changes_per_frame=1,
    )

    selection = select_live_uwb_links(
        positions=BASE_POSITIONS,
        measurements=BASE_MEASUREMENTS,
        options=options,
    )

    assert selected_keys(selection) == [
        "agent_0::agent_1",
        "agent_0::agent_2",
        "agent_1::agent_2",
    ]
    assert selection.diagnostics.added_links == 3


def test_deduplicates_reversed_or_repeated_candidates_by_endpoint_pair() -> None:
    duplicated_measurements = [
        uwb("agent_0", "agent_1", 1.0),
        uwb("agent_1", "agent_0", 1.0),
        uwb("agent_0", "agent_1", 1.0),
    ]
    options = LiveUwbSelectionOptions(
        max_links_per_agent=7,
        max_range_m=2.0,
        add_range_m=1.9,
        drop_range_m=2.2,
        max_graph_changes_per_frame=10,
    )

    selection = select_live_uwb_links(
        positions=BASE_POSITIONS,
        measurements=duplicated_measurements,
        options=options,
        previous_selected_links=[
            SelectedUwbLink(source_id="agent_1", target_id="agent_0"),
        ],
    )

    assert [candidate.key for candidate in selection.candidates] == ["agent_0::agent_1"]
    assert selected_keys(selection) == ["agent_0::agent_1"]


COLLINEAR_POSITIONS = {
    "agent_0": (0.0, 0.0, 0.0),
    "agent_1": (2.0, 0.0, 0.0),
    "agent_2": (4.0, 0.0, 0.0),
}

COLLINEAR_MEASUREMENTS = [
    uwb("agent_0", "agent_1", 2.0),
    uwb("agent_1", "agent_2", 2.0),
    uwb("agent_0", "agent_2", 4.0),
]

COLLINEAR_OPTIONS = LiveUwbSelectionOptions(
    max_links_per_agent=3,
    max_range_m=5.0,
    add_range_m=5.0,
    drop_range_m=5.5,
    max_graph_changes_per_frame=10,
)


def test_rejects_a_link_closing_a_degenerate_collinear_triangle() -> None:
    selection = select_live_uwb_links(
        positions=COLLINEAR_POSITIONS,
        measurements=COLLINEAR_MEASUREMENTS,
        options=COLLINEAR_OPTIONS,
    )

    assert selected_keys(selection) == ["agent_0::agent_1", "agent_1::agent_2"]


def test_drops_a_retained_link_collinear_with_selected_links() -> None:
    previous_links = [
        SelectedUwbLink(
            source_id=measurement.source_id,
            target_id=measurement.target_id,
        )
        for measurement in COLLINEAR_MEASUREMENTS
    ]

    selection = select_live_uwb_links(
        positions=COLLINEAR_POSITIONS,
        measurements=COLLINEAR_MEASUREMENTS,
        options=COLLINEAR_OPTIONS,
        previous_selected_links=previous_links,
    )

    assert selected_keys(selection) == ["agent_0::agent_1", "agent_1::agent_2"]
    assert selection.diagnostics.dropped_links == 1


def test_rejects_nested_collinear_link_without_a_closed_triangle() -> None:
    nested_measurements = [
        uwb("agent_0", "agent_1", 2.0),
        uwb("agent_0", "agent_2", 4.0),
    ]

    selection = select_live_uwb_links(
        positions=COLLINEAR_POSITIONS,
        measurements=nested_measurements,
        options=COLLINEAR_OPTIONS,
        previous_selected_links=[
            SelectedUwbLink(source_id="agent_0", target_id="agent_1"),
        ],
    )

    assert selected_keys(selection) == ["agent_0::agent_1"]


def test_retains_until_drop_range_and_delays_new_until_add_range() -> None:
    boundary_positions = {
        "agent_0": (0.0, 0.0, 0.0),
        "agent_1": (2.05, 0.0, 0.0),
        "agent_2": (1.95, 0.0, 0.0),
    }
    boundary_measurements = [
        uwb("agent_0", "agent_1", 2.05),
        uwb("agent_0", "agent_2", 1.95),
    ]
    options = LiveUwbSelectionOptions(
        max_links_per_agent=2,
        max_range_m=2.0,
        add_range_m=1.9,
        drop_range_m=2.1,
        max_graph_changes_per_frame=10,
    )

    selection = select_live_uwb_links(
        positions=boundary_positions,
        measurements=boundary_measurements,
        options=options,
        previous_selected_links=[
            SelectedUwbLink(source_id="agent_0", target_id="agent_1"),
        ],
    )

    assert selected_keys(selection) == ["agent_0::agent_1"]
    assert selection.diagnostics.added_links == 0


def test_drops_past_drop_range_and_limits_additions_per_frame() -> None:
    moving_positions = {
        "agent_0": (0.0, 0.0, 0.0),
        "agent_1": (2.3, 0.0, 0.0),
        "agent_2": (1.0, 0.0, 0.0),
        "agent_3": (0.0, 0.0, 1.0),
    }
    moving_measurements = [
        uwb("agent_0", "agent_1", 2.3),
        uwb("agent_0", "agent_2", 1.0),
        uwb("agent_0", "agent_3", 1.0),
    ]
    options = LiveUwbSelectionOptions(
        max_links_per_agent=2,
        max_range_m=2.0,
        add_range_m=2.0,
        drop_range_m=2.1,
        max_graph_changes_per_frame=1,
    )

    selection = select_live_uwb_links(
        positions=moving_positions,
        measurements=moving_measurements,
        options=options,
        previous_selected_links=[
            SelectedUwbLink(source_id="agent_0", target_id="agent_1"),
        ],
    )

    assert len(selection.selected_links) == 1
    assert "agent_0::agent_1" not in selected_keys(selection)
    assert selection.diagnostics.dropped_links == 1
    assert selection.diagnostics.added_links == 1


def load_parity_scenarios() -> list[dict]:
    """Load the TypeScript-generated parity fixture scenarios."""
    fixture_payload = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    return fixture_payload["scenarios"]


def all_pair_measurements_from_positions(positions: dict[str, tuple[float, ...]],
                                         sigma_m: float) -> list[LiveUwbMeasurement]:
    """Rebuild the all-pair candidate set the fixture generator used."""
    from swarmfix.scenarios.mission_actions import _agent_sort_key

    ordered_ids = sorted(positions.keys(), key=_agent_sort_key)
    measurements = []
    for source_index, source_id in enumerate(ordered_ids):
        for target_id in ordered_ids[source_index + 1:]:
            source = positions[source_id]
            target = positions[target_id]
            distance_m = math.sqrt(
                sum((s - t) ** 2 for s, t in zip(source, target))
            )
            measurements.append(
                uwb(source_id, target_id, distance_m, sigma_m=sigma_m)
            )
    return measurements


@pytest.mark.parametrize(
    "scenario",
    load_parity_scenarios(),
    ids=lambda scenario: scenario["name"],
)
def test_python_selector_reproduces_typescript_fixture(scenario: dict) -> None:
    positions = {
        agent_id: tuple(position)
        for agent_id, position in scenario["positions"].items()
    }
    fixture_options = scenario["options"]
    unbounded = math.inf
    options = LiveUwbSelectionOptions(
        max_links_per_agent=fixture_options["max_links_per_agent"],
        max_range_m=(
            fixture_options["max_range_m"]
            if fixture_options["max_range_m"] is not None
            else unbounded
        ),
        add_range_m=fixture_options["add_range_m"],
        drop_range_m=fixture_options["drop_range_m"],
        max_graph_changes_per_frame=fixture_options["max_graph_changes_per_frame"],
        min_link_separation_deg=fixture_options["min_link_separation_deg"],
    )
    previous_links = [
        SelectedUwbLink(source_id=link["source_id"], target_id=link["target_id"])
        for link in scenario["previous_selected_links"]
    ]

    selection = select_live_uwb_links(
        positions=positions,
        measurements=all_pair_measurements_from_positions(positions, sigma_m=0.12),
        options=options,
        previous_selected_links=previous_links,
    )

    expected_links = scenario["expected"]["selected_links"]
    actual_summaries = [
        (
            link.source_id,
            link.target_id,
            link.selection_reason,
        )
        for link in selection.selected_links
    ]
    expected_summaries = [
        (
            link["source_id"],
            link["target_id"],
            link["selection_reason"],
        )
        for link in expected_links
    ]
    assert actual_summaries == expected_summaries
    for actual, expected in zip(selection.selected_links, expected_links):
        assert actual.measured_distance_m == pytest.approx(
            expected["measured_distance_m"],
            rel=1e-9,
        )
        assert actual.sigma_m == expected["sigma_m"]
    expected_diagnostics = scenario["expected"]["diagnostics"]
    actual_diagnostics = selection.diagnostics.model_dump()
    for field_name, expected_value in expected_diagnostics.items():
        assert actual_diagnostics[field_name] == expected_value, field_name
