"""Default performance thresholds for SwarmFix observability."""

VIEWER_FRAME_SLOW_MS = 33.0
VIEWER_SCENE_BUILD_SLOW_MS = 20.0
VIEWER_RENDER_SLOW_MS = 16.0
LIVE_SOLVE_SLOW_MS = 250.0
PYTHON_LEAST_SQUARES_SLOW_MS = 200.0
STALE_SOLVER_WARNING_MS = 1000.0
